name = "ExpFit"
uuid = "3e354d20-bd3f-44fe-967b-b5188f355960"
authors = ["Hideaki Takahashi <takahashi.hideaki.w33@kyoto-u.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AMRVW = "1.2.1"
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
