name = "ExpFit"
uuid = "3e354d20-bd3f-44fe-967b-b5188f355960"
authors = ["Hideaki Takahashi <takahashi.hideaki.w33@kyoto-u.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RationalFunctionApproximation = "c92886a3-cb30-4e18-b84f-372dde475ecc"

[compat]
AMRVW = "1.2.1"
FFTW = "1.8.1"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
RationalFunctionApproximation = "0.1.4"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
